---
- hosts: aws
  become: true
  vars_files:
   - vars.yaml

  tasks:
   - name: Install aptitude using apt
     apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

   - name: Install required system packages
     apt: name={{ item }} state=latest update_cache=yes
     loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

   - name: Add Docker GPG apt Key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

   - name: Add Docker Repository
     apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu bionic stable
       state: present

   - name: Update apt and install docker-ce
     apt: update_cache=yes name=docker-ce state=latest

   - name: Install Docker Module for Python
     pip:
       name: docker
   
   # - name: Copy Dockerfile
   #   copy: src=Dockerfile dest=/tmp/path/
      
   - name: build dockerfile
     docker_image:
      path: .
      name: shaymaa12/nodeapp_ansible_try
      tag: v1

    # - name: Tag and push to docker hub
    #   docker_image:
    #     name: shaymaa12/nodeapp_ansible_try
    #     repository: 
    #     tag: v1
    #     push: yes
          
   # - name: Pull default Docker image
   #   docker_image:
   #     name: "{{ container_image }}"
   #     source: pull

   # - name: Create default containers
   #   docker_container:
   #     name: "{{ container_name }}{{ item }}"
   #     image: "{{ container_image }}"
   #     command: "{{ container_command }}"
   #     state: present
   #   with_sequence: count={{ containers }}
