---
- hosts: aws
  become: true
  tasks:
   - name: Add Docker GPG apt Key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

   - name: Add Docker Repository
     apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu bionic stable
       state: present

   - name: Update apt and install docker-ce
     apt: update_cache=yes name=docker-ce state=latest

   - name: Pull Docker image
     docker_image:
       name: {{ username }}/nodeapp_ansible:{{ CIRCLE_BUILD_NUM }}
       source: pull

   - name: Create container
     docker_container:
       name: "node"
       image: {{ username }}/nodeapp_ansible:{{ CIRCLE_BUILD_NUM }}
       state: present
       ports:
         - "3000:3000"

